### ISSUE TITLE
GetProductFeedback ignores setProduct filter

### ISSUE THREAD

**Issue by nobuttsalex** [ekomi-dev/ekomi-api#1]
This seems to be a new issue as I previously had no problems but now even when I set the product id all product reviews are returned and the filter is ignored

```
$apiCall = new GetProductFeedback();
$apiCall->setProduct('product-id');
$results = $api->exec($apiCall);
```

**Comment by smytsyk-dev** [comment]
Hi,
I'm sorry but currently I don't have an access to the API. Try to follow API Doc if you have it.
You also should cache response on your side and don't request eKomi server too often, in other case you could be blocked.
